// Generated by https://quicktype.io

export interface HeroResponse {
  id: number;
  name: string;
  localized_name: string;
  primary_attr: PrimaryAttr;
  attack_type: AttackType;
  roles: Role[];
  legs: number;
}

export enum AttackType {
  Melee = 'Melee',
  Ranged = 'Ranged',
}

export enum PrimaryAttr {
  Agi = 'agi',
  Int = 'int',
  Str = 'str',
}

export enum Role {
  Carry = 'Carry',
  Disabler = 'Disabler',
  Durable = 'Durable',
  Escape = 'Escape',
  Initiator = 'Initiator',
  Jungler = 'Jungler',
  Nuker = 'Nuker',
  Pusher = 'Pusher',
  Support = 'Support',
}

//creada por mi
export interface SimpleHero {
  id: number;
  name: string;
  picture: string;
  color?: string;
}
